### ISSUE TITLE
Question about the training on CAMERA dataset

### ISSUE THREAD

**Issue by LSerene** [lolrudy/GPV_Pose#13]
Thanks for the code sharing and the impressive work.

I am trying to train the code on REAL275 and CAMERA datasets by myself. I trained two networks by setting the `dataset` to `Real` and `CAMERA` in `config.py`. The result trained on REAL275 is good. However, the one trained on the CAMERA dataset did not seem well. The following are the results on CAMERA:

```
average mAP:
3D IoU at 25: 95.0
3D IoU at 50: 92.8
3D IoU at 75: 85.1
5 degree, 2cm: 61.9
5 degree, 5cm: 73.0
10 degree, 2cm: 71.1
10 degree, 5cm: 85.8
10 degree, 10cm: 87.3
```
I am wondering should the hyperparameters be adjusted for training the CAMERA dataset, or are there any other clues for this? Thank you so much!

**Comment by lolrudy** [comment]
Sorry for waiting. Since CAMERA dataset is larger than Real, more epochs are needed for convergence. The training epoch is 300 on CAMERA. FYI, I upload the trained weights.

**Comment by LSerene** [comment]
Thanks!

**Comment by wxycwymds** [comment]
> Thanks for the code sharing and the impressive work.
> 
> I am trying to train the code on REAL275 and CAMERA datasets by myself. I trained two networks by setting the `dataset` to `Real` and `CAMERA` in `config.py`. The result trained on REAL275 is good. However, the one trained on the CAMERA dataset did not seem well. The following are the results on CAMERA:
> 
> ```
> average mAP:
> 3D IoU at 25: 95.0
> 3D IoU at 50: 92.8
> 3D IoU at 75: 85.1
> 5 degree, 2cm: 61.9
> 5 degree, 5cm: 73.0
> 10 degree, 2cm: 71.1
> 10 degree, 5cm: 85.8
> 10 degree, 10cm: 87.3
> ```
> 
> I am wondering should the hyperparameters be adjusted for training the CAMERA dataset, or are there any other clues for this? Thank you so much!

Hi！when I train the code on REAL275，I got this problem。
![image](https://github.com/lolrudy/GPV_Pose/assets/111268038/51c0080f-f10d-434c-941a-51f5fbc904e3)
I guess that maybe my virtual environment has something wrong，I will be grateful if you can give me the requirement.txt of your virtual environment. Thank you so much!

**Comment by LSerene** [comment]
> > Thanks for the code sharing and the impressive work.
> > I am trying to train the code on REAL275 and CAMERA datasets by myself. I trained two networks by setting the `dataset` to `Real` and `CAMERA` in `config.py`. The result trained on REAL275 is good. However, the one trained on the CAMERA dataset did not seem well. The following are the results on CAMERA:
> > ```
> > average mAP:
> > 3D IoU at 25: 95.0
> > 3D IoU at 50: 92.8
> > 3D IoU at 75: 85.1
> > 5 degree, 2cm: 61.9
> > 5 degree, 5cm: 73.0
> > 10 degree, 2cm: 71.1
> > 10 degree, 5cm: 85.8
> > 10 degree, 10cm: 87.3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am wondering should the hyperparameters be adjusted for training the CAMERA dataset, or are there any other clues for this? Thank you so much!
> 
> Hi！when I train the code on REAL275，I got this problem。 ![image](https://user-images.githubusercontent.com/111268038/244398386-51c0080f-f10d-434c-941a-51f5fbc904e3.png) I guess that maybe my virtual environment has something wrong，I will be grateful if you can give me the requirement.txt of your virtual environment. Thank you so much!

In my experiments, the `total_loss` returned `nan` occasionally due to the failure plane normal fitting. I added an 'nan' value detection function before the backward function. The training will directly go to next iteration when `nan' is detected. I hope this helps.

**Comment by wxycwymds** [comment]
@LSerene  Thank you so much！I will try to add the  'nan' value detection function,but I will be grateful if you can show me the code of yours .  By the way，have you change any hyper-parameter？
