### ISSUE TITLE
Quires about the experiment on LineMOD dataset

### ISSUE THREAD

**Issue by Lynne-Zheng-Linfang** [lolrudy/GPV_Pose#15]
Hi, thanks for sharing the code. I am planning to compare my algorithm with the GPV-Pose. About the experiment on the LineMOD dataset, is the evaluation mask trained using MaskRCNN? Also, would you like to share the resulting masks for a fair comparison? Thanks!

**Comment by lolrudy** [comment]
We use the masks provided by GDRN (https://github.com/THU-DA-6D-Pose-Group/GDR-Net).

**Comment by Lynne-Zheng-Linfang** [comment]
Thanks! One more question, please. Is the GPV-Net trained using real images only or the full LineMOD dataset setting as the GDRN?

> We use the masks provided by GDRN (https://github.com/THU-DA-6D-Pose-Group/GDR-Net).

**Comment by lolrudy** [comment]
Sorry that I do not remember clearly. It should be the same setting as GDRN.

**Comment by Lynne-Zheng-Linfang** [comment]
Thanks!
