### ISSUE TITLE
where/how can I find/generate "mug_handle.pkl"?

### ISSUE THREAD

**Issue by dedoogong** [lolrudy/GPV_Pose#2]
Hello~! Thank you very much for your sharing. 
I already handled all SPD, FS-Net, Dualpose repos before, but I didn't see "mug_handle.pkl" which is required for training your model~
Please let me know about it~

Thanks!

**Comment by lolrudy** [comment]
Thanks for your interest. I have uploaded the file.

**Comment by Huo-Yukang** [comment]
> Thanks for your interest. I have uploaded the file.

Why can't I find the mug_meta.pkl and real_test.pkl you uploaded? What folder did you upload it to?
Thanks!
