### ISSUE TITLE
A question regarding the loss.

### ISSUE THREAD

**Issue by ran894694447** [lolrudy/GPV_Pose#20]
Thank you for your great work, but I have a small question regarding some loss terms. What is the geometric meaning of the formula enclosed in the red box in the diagram below? Additionally, for the second part of Equation (14), why is it i∈|B|, or in other words, what does |B| represent?Looking forward to your response.
![1](https://github.com/lolrudy/GPV_Pose/assets/104256115/bf04cbfa-d3c4-48bf-a916-7db703e4d1a0)

**Comment by shangbuhuan13** [comment]
这里面是把t当做bbox的中心了，t是bbox的中心，所以它到相对的两个面的距离是相等的。那个B的定义是前面的，实际上就是bbox的6个面

**Comment by ran894694447** [comment]
> 这里面是把t当做bbox的中心了，t是bbox的中心，所以它到相对的两个面的距离是相等的。那个B的定义是前面的，实际上就是bbox的6个面

明白了，当时脑子有点宕机了，谢谢
