### ISSUE TITLE
your requirements may contain some @, I can not know its current version

### ISSUE THREAD

**Issue by yuheyuan** [lolrudy/GPV_Pose#9]
for example
```txt
blessings @ file:///tmp/build/80754af9/blessings_1614076441300/work
```
it may occur in your requirements

this may solve it problem
```python
pip list --format=freeze > requirements.txt
```

**Comment by lolrudy** [comment]
I update the requirements file. The environment is different from the original version since the computer system is reinstalled and I have to reinstall all packages. I hasn't tested the new environment thoroughly, so some packages might be missing.
